name: Continuous Integration
on:
  pull_request: {}
  push:
    branches:
      - '[0-9]+.[0-9]+.x'
      - 'refs/pull/*'
    tags: {}

jobs:
  linting:
    runs-on: "node:current-alpine"
    steps:
      - uses: actions/checkout@v2
      - name: Install node modules
        run: npm install --no-save
      - name: Run ESLint
        run: node_modules/.bin/eslint index.js src
