name: "Continuous Integration"
on:
  pull_request: {}
  push:
    branches:
      - '[0-9]+.[0-9]+.x'
      - 'refs/pull/*'
    tags: {}

jobs:
  linting:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v2"
      - uses: "actions/setup-node@v2"
        with:
          check-latest: true
      - name: "Install node modules"
        run: "npm install --no-save"
      - name: Run ESLint
        run: "node_modules/.bin/eslint index.js src"
